// Package stock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package stock

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Message string `json:"message"`
}

// NewStockItem defines model for NewStockItem.
type NewStockItem struct {
	Name string `json:"name" validate:"required,lt=100"`
}

// NewStockLocation defines model for NewStockLocation.
type NewStockLocation struct {
	Name string `json:"name" validate:"required,lt=100"`
}

// BadRequest defines model for BadRequest.
type BadRequest = BadRequestResponse

// Created defines model for Created.
type Created struct {
	Id openapi_types.UUID `json:"id" validate:"required"`
}

// PostStockItemJSONRequestBody defines body for PostStockItem for application/json ContentType.
type PostStockItemJSONRequestBody = NewStockItem

// PutStockItemJSONRequestBody defines body for PutStockItem for application/json ContentType.
type PutStockItemJSONRequestBody = NewStockItem

// PostStockLocationJSONRequestBody defines body for PostStockLocation for application/json ContentType.
type PostStockLocationJSONRequestBody = NewStockLocation

// PutStockLocationJSONRequestBody defines body for PutStockLocation for application/json ContentType.
type PutStockLocationJSONRequestBody = NewStockLocation

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Stock Item
	// (POST /stock/items)
	PostStockItem(ctx echo.Context) error
	// Delete Stock Item
	// (DELETE /stock/items/{stockItemId})
	DeleteStockItem(ctx echo.Context, stockItemId openapi_types.UUID) error
	// Update Stock Item
	// (PUT /stock/items/{stockItemId})
	PutStockItem(ctx echo.Context, stockItemId openapi_types.UUID) error
	// Create Stock Location
	// (POST /stock/locations)
	PostStockLocation(ctx echo.Context) error
	// Delete Stock Location
	// (DELETE /stock/locations/{StockLocationId})
	DeleteStockLocation(ctx echo.Context, stockLocationId openapi_types.UUID) error
	// Update Stock Location
	// (PUT /stock/locations/{StockLocationId})
	PutStockLocation(ctx echo.Context, stockLocationId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) PostStockItem(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStockItem(ctx)
	return err
}

// DeleteStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStockItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "stockItemId" -------------
	var stockItemId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "stockItemId", runtime.ParamLocationPath, ctx.Param("stockItemId"), &stockItemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter stockItemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStockItem(ctx, stockItemId)
	return err
}

// PutStockItem converts echo context to params.
func (w *ServerInterfaceWrapper) PutStockItem(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "stockItemId" -------------
	var stockItemId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "stockItemId", runtime.ParamLocationPath, ctx.Param("stockItemId"), &stockItemId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter stockItemId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutStockItem(ctx, stockItemId)
	return err
}

// PostStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) PostStockLocation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStockLocation(ctx)
	return err
}

// DeleteStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStockLocation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "StockLocationId" -------------
	var stockLocationId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "StockLocationId", runtime.ParamLocationPath, ctx.Param("StockLocationId"), &stockLocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter StockLocationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStockLocation(ctx, stockLocationId)
	return err
}

// PutStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) PutStockLocation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "StockLocationId" -------------
	var stockLocationId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "StockLocationId", runtime.ParamLocationPath, ctx.Param("StockLocationId"), &stockLocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter StockLocationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutStockLocation(ctx, stockLocationId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/stock/items", wrapper.PostStockItem)
	router.DELETE(baseURL+"/stock/items/:stockItemId", wrapper.DeleteStockItem)
	router.PUT(baseURL+"/stock/items/:stockItemId", wrapper.PutStockItem)
	router.POST(baseURL+"/stock/locations", wrapper.PostStockLocation)
	router.DELETE(baseURL+"/stock/locations/:StockLocationId", wrapper.DeleteStockLocation)
	router.PUT(baseURL+"/stock/locations/:StockLocationId", wrapper.PutStockLocation)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTU/jPBD+K9G879FN0pa9RNoDsKxUgQCB9oR6sJKh9W5iG3tCQVX++8pOP9Kmpa2W",
	"FRV7q+1nPp+ZJ51CqgqtJEqykEzBoNVKWvSHM57d4VOJltwpVZJQ+p9c61yknISS0U+rpLuz6RgL7n79",
	"b/AREvgvWrqO6lcbLV3ezSJBVVUMMrSpEdp5hMQFDuaRKwbnBjlhdlAS2iiNhkRdifDGj8oUnCCBshQZ",
	"MKBXjZCAJSPkCBi8dBTXopOqDEcoO/hChneIj7yLZ56LjJMzMPhUCoNZnfrilDy4OMMN9cwLqBgMJKGR",
	"PL9H84zmwhhlnPdV/BwU1KighlUMrhV9V6XM2ibXioL6qWJwc9kG3FyCS2xGxCq9Cy5ajSvQWj7yD6vd",
	"Wq98Dhy6LHFyTyr9NSAs2i4lL7y/gr+Ioiwg6cbxn3PBcvrajeM2JT5cM6srVQ/NsWTmroV8VG3KfLqB",
	"62JwejsABrlIcUZTnSucap6OMeiFMTAoTQ4JjIl0EkWTySTk/jVUZhTNTG10NTi/uL6/6PTCOBxTkbt5",
	"IUE5bgr4jMbWuXTDOIwdVmmUXAtIoB/GYR8YaE5jX3xknX0kCAt/1qpWjk3LECxjgXdqPCmDDBK4VZaW",
	"A1Q3DS2dqez13YRoZUbXqCFTor9oaGEv7m5zucBFjT0/iePd+IbAVgy+7GOyST/8XpdFwc3rxv669yY3",
	"0dTOSx9kVc1QjoRtrr75+7e4qhFNtjQ3vEBCYyF5mIJwftyIAJsPbSM6rPedNfh7W6+ratjiaI8GOh10",
	"9Jzshi7U9v3IaTe0YqDLDWvyQ2e71qSkD+z7MazkAXQfvI0fNSFt3hvrm8++XfvK6+Jbt1ViG4i/yeki",
	"zOeV2kaJbb6i6UobDpHdrRw2pLeB2S0Da5n80xK8JG0fGd6+TiUdAQ/Hsr6fXpZX22G9UU3zyl9wt/35",
	"WFlKuv1eH6ph9TsAAP//2U0mPm8PAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
