// Package location provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package location

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Message string `json:"message"`
}

// NewStockLocation defines model for NewStockLocation.
type NewStockLocation struct {
	Name string `json:"name" validate:"required,lt=100"`
}

// BadRequest defines model for BadRequest.
type BadRequest = BadRequestResponse

// Created defines model for Created.
type Created struct {
	Id openapi_types.UUID `json:"id" validate:"required"`
}

// PostStockLocationJSONRequestBody defines body for PostStockLocation for application/json ContentType.
type PostStockLocationJSONRequestBody = NewStockLocation

// PutStockLocationJSONRequestBody defines body for PutStockLocation for application/json ContentType.
type PutStockLocationJSONRequestBody = NewStockLocation

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Stock Location
	// (POST /stock/locations)
	PostStockLocation(ctx echo.Context) error
	// Delete Stock Location
	// (DELETE /stock/locations/{StockLocationId})
	DeleteStockLocation(ctx echo.Context, stockLocationId openapi_types.UUID) error
	// Update Stock Location
	// (PUT /stock/locations/{StockLocationId})
	PutStockLocation(ctx echo.Context, stockLocationId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) PostStockLocation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStockLocation(ctx)
	return err
}

// DeleteStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteStockLocation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "StockLocationId" -------------
	var stockLocationId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "StockLocationId", runtime.ParamLocationPath, ctx.Param("StockLocationId"), &stockLocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter StockLocationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteStockLocation(ctx, stockLocationId)
	return err
}

// PutStockLocation converts echo context to params.
func (w *ServerInterfaceWrapper) PutStockLocation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "StockLocationId" -------------
	var stockLocationId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "StockLocationId", runtime.ParamLocationPath, ctx.Param("StockLocationId"), &stockLocationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter StockLocationId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutStockLocation(ctx, stockLocationId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/stock/locations", wrapper.PostStockLocation)
	router.DELETE(baseURL+"/stock/locations/:StockLocationId", wrapper.DeleteStockLocation)
	router.PUT(baseURL+"/stock/locations/:StockLocationId", wrapper.PutStockLocation)

}
