// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	StockItem     string
	StockLocation string
}{
	StockItem:     "stock_item",
	StockLocation: "stock_location",
}
