openapi: 3.0.3
info:
  title: Stock Item API
  version: 1.0.0
paths:
  /stock/items:
    post:
      summary: Create Stock Item
      description: Create Stock Item
      operationId: PostStockItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewStockItem"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /stock/items/{stockitemId}:
    put:
      summary: Update Stock Item
      description: Update Stock Item
      operationId: PutStockItem
      parameters:
        - name: stockitemId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/StockItemId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewStockItem"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      summary: Delete Stock Item
      description: Delete Stock Item
      operationId: DeleteStockItem
      parameters:
        - name: stockitemId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/StockItemId"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  responses:
    OK:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StockItem"
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StockItem"
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestResponse"
    NotFound:
      description: Not Found
    InternalServerError:
      description: Internal Server Error
  schemas:
    BadRequestResponse:
      required:
        - message
      properties:
        message:
          type: string
    StockItem:
      allOf:
        - $ref: "#/components/schemas/StockItemId"
        - $ref: "#/components/schemas/NewStockItem"
    NewStockItem:
      allOf:
        - $ref: "#/components/schemas/StockItemName"
    StockItemId:
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          x-oapi-codegen-extra-tags:
            validate: required
    StockItemName:
      required:
        - name
      properties:
        name:
          type: string
          minimum: 1
          maximum: 100
          x-oapi-codegen-extra-tags:
            validate: required,gte=1,lt=100
